In [8]:
# !pip install -r to_do.txt

In [9]:
#!pip install protobuf-to-dict

In [10]:
import sys
print(sys.version)

3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]

In [11]:
import numpy as np
import pandas as pd

In [ ]:
#!python atac_script.py

In [ ]:
#pip install protobuf3-to-dict

In [ ]:
df = pd.read_csv(r"./tu_1693992630.csv", sep = ";")

In [ ]:
df = pd.read_csv(r"./tu_1693992630.csv", sep = ";")

In [31]:
!python atac_script_loop.py

0
Hello
0 12.117243766784668
1
1 10.020272970199585
2
2 10.926259756088257
3
3 21.09154510498047
4
Trying again
IncompleteRead(751530 bytes read, 8245 more expected)
4 13.916886329650879
5
Trying again
DecodeError('Error parsing message')
5 26.79063057899475
6
6 10.803873538970947
7
7 20.972089290618896
8
Trying again
IncompleteRead(743420 bytes read, 12307 more expected)
8 8.46732473373413
9
9 10.54085922241211
10
10 21.888716459274292
11
11 10.9142324924469
12
Trying again
DecodeError('Error parsing message')
12 9.007304191589355
13
13 11.164927005767822
14
14 10.936427593231201
15
15 19.41177749633789

In [33]:
!python atac_script_loop.py

^C

In [14]:
df1 = pd.read_csv(r".\feeddata\tu_1693996531.csv", sep = ";")

In [12]:
df2 = pd.read_csv(r".\feeddata\tu_1693996620.csv", sep = ";")

In [15]:
df1.head()

,id,isDeleted,tripUpdate.trip.tripId,tripUpdate.trip.startTime,tripUpdate.trip.startDate,tripUpdate.trip.routeId,tripUpdate.trip.directionId,tripUpdate.stopTimeUpdate,tripUpdate.vehicle.id,tripUpdate.vehicle.label,tripUpdate.timestamp,tripUpdate.delay,max_time
0,1,False,0#723-17,12:30:00,20230906,087,0.0,"[{'stopSequence': 9, 'arrival': {'delay': -184...",194,243,1693996512,-178.0,1693996531
1,2,False,0#725-14,12:18:00,20230906,089,0.0,"[{'stopSequence': 16, 'arrival': {'delay': -13...",197,246,1693996505,-144.0,1693996531
2,3,False,0#4512-12,12:18:00,20230906,870,1.0,"[{'stopSequence': 17, 'arrival': {'delay': -12...",199,248,1693996520,-134.0,1693996531
3,4,False,0#4687-8,12:20:00,20230906,228,0.0,"[{'stopSequence': 17, 'arrival': {'delay': -50...",202,251,1693996508,-78.0,1693996531
4,5,False,0#4514-11,12:16:00,20230906,870,0.0,"[{'stopSequence': 19, 'arrival': {'delay': -48...",211,260,1693996512,-464.0,1693996531

In [16]:
df2.head()

,id,isDeleted,tripUpdate.trip.tripId,tripUpdate.trip.startTime,tripUpdate.trip.startDate,tripUpdate.trip.routeId,tripUpdate.trip.directionId,tripUpdate.stopTimeUpdate,tripUpdate.vehicle.id,tripUpdate.vehicle.label,tripUpdate.timestamp,tripUpdate.delay,max_time
0,1,False,0#723-17,12:30:00,20230906,087,0.0,"[{'stopSequence': 10, 'arrival': {'delay': -30...",194,243,1693996574,-226.0,1693996620
1,2,False,0#725-14,12:18:00,20230906,089,0.0,"[{'stopSequence': 17, 'arrival': {'delay': -17...",197,246,1693996567,-148.0,1693996620
2,3,False,0#4512-12,12:18:00,20230906,870,1.0,"[{'stopSequence': 18, 'arrival': {'delay': -74...",199,248,1693996582,-114.0,1693996620
3,4,False,0#4687-8,12:20:00,20230906,228,0.0,"[{'stopSequence': 17, 'arrival': {'delay': -26...",202,251,1693996570,-42.0,1693996620
4,5,False,0#2927-10,12:54:00,20230906,713,0.0,"[{'stopSequence': 1, 'departure': {'delay': -1...",206,255,1693996583,-1062.0,1693996620

In [17]:
dftotal = pd.concat([df1,df2])

In [18]:
dftotal

,id,isDeleted,tripUpdate.trip.tripId,tripUpdate.trip.startTime,tripUpdate.trip.startDate,tripUpdate.trip.routeId,tripUpdate.trip.directionId,tripUpdate.stopTimeUpdate,tripUpdate.vehicle.id,tripUpdate.vehicle.label,tripUpdate.timestamp,tripUpdate.delay,max_time
0,1,False,0#723-17,12:30:00,20230906,087,0.0,"[{'stopSequence': 9, 'arrival': {'delay': -184...",194,243,1693996512,-178.0,1693996531
1,2,False,0#725-14,12:18:00,20230906,089,0.0,"[{'stopSequence': 16, 'arrival': {'delay': -13...",197,246,1693996505,-144.0,1693996531
2,3,False,0#4512-12,12:18:00,20230906,870,1.0,"[{'stopSequence': 17, 'arrival': {'delay': -12...",199,248,1693996520,-134.0,1693996531
3,4,False,0#4687-8,12:20:00,20230906,228,0.0,"[{'stopSequence': 17, 'arrival': {'delay': -50...",202,251,1693996508,-78.0,1693996531
4,5,False,0#4514-11,12:16:00,20230906,870,0.0,"[{'stopSequence': 19, 'arrival': {'delay': -48...",211,260,1693996512,-464.0,1693996531
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,False,0#5137-8,12:39:00,20230906,3NAV,1.0,"[{'stopSequence': 1, 'departure': {'delay': -4...",4622,837,1693996581,-598.0,1693996620
886,887,False,0#1923-10,12:06:00,20230906,44,1.0,"[{'stopSequence': 26, 'arrival': {'delay': -19...",4624,839,1693996589,-130.0,1693996620
887,888,False,0#4636-9,11:31:00,20230906,62,1.0,"[{'stopSequence': 31, 'arrival': {'delay': 104...",4625,840,1693996572,954.0,1693996620
888,889,False,0#2068-9,12:40:00,20230906,490,1.0,"[{'stopSequence': 1, 'departure': {'delay': -1...",4626,841,1693996579,-228.0,1693996620
889,890,False,0#4643-8,12:16:00,20230906,62,0.0,"[{'stopSequence': 14, 'arrival': {'delay': -24...",4628,843,1693996565,-210.0,1693996620

In [19]:
len(df1)

877

In [21]:
len(df2)

890

In [23]:
len(dftotal)

1767

In [24]:
890+877

1767

In [25]:
dftotal.head()

,id,isDeleted,tripUpdate.trip.tripId,tripUpdate.trip.startTime,tripUpdate.trip.startDate,tripUpdate.trip.routeId,tripUpdate.trip.directionId,tripUpdate.stopTimeUpdate,tripUpdate.vehicle.id,tripUpdate.vehicle.label,tripUpdate.timestamp,tripUpdate.delay,max_time
0,1,False,0#723-17,12:30:00,20230906,087,0.0,"[{'stopSequence': 9, 'arrival': {'delay': -184...",194,243,1693996512,-178.0,1693996531
1,2,False,0#725-14,12:18:00,20230906,089,0.0,"[{'stopSequence': 16, 'arrival': {'delay': -13...",197,246,1693996505,-144.0,1693996531
2,3,False,0#4512-12,12:18:00,20230906,870,1.0,"[{'stopSequence': 17, 'arrival': {'delay': -12...",199,248,1693996520,-134.0,1693996531
3,4,False,0#4687-8,12:20:00,20230906,228,0.0,"[{'stopSequence': 17, 'arrival': {'delay': -50...",202,251,1693996508,-78.0,1693996531
4,5,False,0#4514-11,12:16:00,20230906,870,0.0,"[{'stopSequence': 19, 'arrival': {'delay': -48...",211,260,1693996512,-464.0,1693996531