In [1]:
import pandas as pd
import os
import numpy
pd.set_option()

In [8]:
tu_feed  = pd.read_csv('./output_data/tu_feed.csv')
tu_feed = tu_feed.rename(columns={'tripUpdate.trip.tripId': 'trip_id'})
vp_feed  = pd.read_csv('./output_data/vp_feed.csv')
vp_feed = vp_feed.rename(columns={'vehicle.trip.tripId': 'trip_id'})

In [9]:
tu_feed.shape

(205711, 13)

In [10]:
vp_feed.shape

(205675, 19)

In [11]:
atac_state = pd.read_csv(r"./output_data/atac_state_full.csv")

/var/folders/wp/hp437k1x56n9y9m31x7fsx640000gn/T/ipykernel_6496/3109705268.py:1: DtypeWarning: Columns (3,8) have mixed types. Specify dtype option on import or set low_memory=False.
  atac_state = pd.read_csv(r"./output_data/atac_state_full.csv")

In [12]:
atac_state.shape

(4039455, 11)

In [15]:
atac_state.merge(tu_feed, on = "trip_id",how = "inner").sort_values(["trip_id",

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,shape_dist_traveled,timepoint,route_id,service_id,...,tripUpdate.trip.startTime,tripUpdate.trip.startDate,tripUpdate.trip.routeId,tripUpdate.trip.directionId,tripUpdate.stopTimeUpdate,tripUpdate.vehicle.id,tripUpdate.vehicle.label,tripUpdate.timestamp,tripUpdate.delay,max_time
0,0#2196-12,12:24:00,12:24:00,74761,14,NaN,7841,1,507,0#9,...,12:02:00,20230907,507,1.0,"[{'stopSequence': 1, 'departure': {'delay': -1...",3967,2117,2023-09-07 09:58:48,-196.0,2023-09-07 09:59:02
1,0#2196-12,12:24:00,12:24:00,74761,14,NaN,7841,1,507,0#9,...,12:02:00,20230907,507,1.0,"[{'stopSequence': 1, 'departure': {'delay': -2...",3967,2117,2023-09-07 09:56:44,-320.0,2023-09-07 09:57:02
2,0#2196-12,12:24:00,12:24:00,74761,14,NaN,7841,1,507,0#9,...,12:02:00,20230907,507,1.0,"[{'stopSequence': 1, 'departure': {'delay': -5...",3967,2117,2023-09-07 09:52:36,-568.0,2023-09-07 09:53:01
3,0#2196-12,12:24:00,12:24:00,74761,14,NaN,7841,1,507,0#9,...,12:02:00,20230907,507,1.0,"[{'stopSequence': 1, 'departure': {'delay': -2...",3967,2117,2023-09-07 09:57:47,-258.0,2023-09-07 09:58:01
4,0#2196-12,12:24:00,12:24:00,74761,14,NaN,7841,1,507,0#9,...,12:02:00,20230907,507,1.0,"[{'stopSequence': 1, 'departure': {'delay': -5...",3967,2117,2023-09-07 09:51:35,-630.0,2023-09-07 09:52:02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6551480,0#3254-2,15:18:38,15:18:38,78862,2,NaN,435,0,775,0#9,...,15:17:00,20230906,775,1.0,"[{'stopSequence': 1, 'departure': {'delay': -3...",715,2678,2023-09-06 13:15:41,-150.0,2023-09-06 13:16:32
6551481,0#3254-2,15:20:18,15:20:18,78863,3,NaN,868,0,775,0#9,...,15:17:00,20230906,775,1.0,"[{'stopSequence': 1, 'departure': {'delay': -6...",715,2678,2023-09-06 13:15:10,-110.0,2023-09-06 13:15:31
6551482,0#3254-2,15:20:18,15:20:18,78863,3,NaN,868,0,775,0#9,...,15:17:00,20230906,775,1.0,"[{'stopSequence': 1, 'departure': {'delay': -3...",715,2678,2023-09-06 13:15:41,-150.0,2023-09-06 13:16:32
6551483,0#3254-2,15:23:00,15:23:00,74654,4,NaN,1575,1,775,0#9,...,15:17:00,20230906,775,1.0,"[{'stopSequence': 1, 'departure': {'delay': -6...",715,2678,2023-09-06 13:15:10,-110.0,2023-09-06 13:15:31
6551484,0#3254-2,15:23:00,15:23:00,74654,4,NaN,1575,1,775,0#9,...,15:17:00,20230906,775,1.0,"[{'stopSequence': 1, 'departure': {'delay': -3...",715,2678,2023-09-06 13:15:41,-150.0,2023-09-06 13:16:32

In [19]:
df_tu_total = df_tu_total.rename(columns={'tripUpdate.trip.tripId': 'trip_id'})
df_tu_total

,id,isDeleted,trip_id,tripUpdate.trip.startTime,tripUpdate.trip.startDate,tripUpdate.trip.routeId,tripUpdate.trip.directionId,tripUpdate.stopTimeUpdate,tripUpdate.vehicle.id,tripUpdate.vehicle.label,tripUpdate.timestamp,tripUpdate.delay,max_time
0,1,False,0#723-21,14:30:00,20230906,087,0.0,"[{'stopSequence': 1, 'departure': {'delay': -3...",194,0243,2023-09-06 12:24:14,-358.0,2023-09-06 12:24:32
1,2,False,0#725-17,14:03:00,20230906,089,1.0,"[{'stopSequence': 20, 'arrival': {'delay': -52...",197,0246,2023-09-06 12:24:07,-508.0,2023-09-06 12:24:32
2,3,False,0#4512-14,14:05:00,20230906,870,1.0,"[{'stopSequence': 18, 'arrival': {'delay': 20,...",199,0248,2023-09-06 12:24:22,-48.0,2023-09-06 12:24:32
3,4,False,0#4687-9,13:39:00,20230906,228,0.0,"[{'stopSequence': 43, 'arrival': {'delay': -71...",202,0251,2023-09-06 12:24:11,-720.0,2023-09-06 12:24:32
4,5,False,0#4689-9,14:06:00,20230906,228,0.0,"[{'stopSequence': 21, 'arrival': {'delay': -37...",203,0252,2023-09-06 12:24:10,-406.0,2023-09-06 12:24:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205706,857,False,0#1923-12,14:00:00,20230906,44,1.0,"[{'stopSequence': 32, 'arrival': {'delay': -19...",4624,0839,2023-09-06 12:34:49,-192.0,2023-09-06 12:35:31
205707,858,False,0#4636-12,14:34:00,20230906,62,0.0,"[{'stopSequence': 1, 'departure': {'delay': 10...",4625,0840,2023-09-06 12:35:05,40.0,2023-09-06 12:35:31
205708,859,False,0#2068-10,13:47:00,20230906,490,0.0,"[{'stopSequence': 34, 'arrival': {'delay': -27...",4626,0841,2023-09-06 12:35:24,-272.0,2023-09-06 12:35:31
205709,860,False,0#47-11,13:42:00,20230906,H,0.0,"[{'stopSequence': 1, 'departure': {'delay': 29...",4627,0842,2023-09-06 12:34:53,2900.0,2023-09-06 12:35:31
205710,861,False,0#4643-10,14:17:00,20230906,62,0.0,"[{'stopSequence': 6, 'arrival': {'delay': 662,...",4628,0843,2023-09-06 12:35:30,648.0,2023-09-06 12:35:31

In [20]:
atac_state.merge(df_tu_total, on = "trip_id",how = "inner")

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, shape_dist_traveled, timepoint, route_id, service_id, trip_headsign, id, isDeleted, tripUpdate.trip.startTime, tripUpdate.trip.startDate, tripUpdate.trip.routeId, tripUpdate.trip.directionId, tripUpdate.stopTimeUpdate, tripUpdate.vehicle.id, tripUpdate.vehicle.label, tripUpdate.timestamp, tripUpdate.delay, max_time]
Index: []

[0 rows x 23 columns]